defaults:
  - agent: sac_fork
  - _self_

env: BipedalWalker-v3
#env: BipedalWalkerHardcore-v3

experiment: test_exp

num_train_steps: 1e6
max_episode_steps: 1500
num_seed_steps: 5000
replay_buffer_capacity: ${num_train_steps}
batch_size: 1024

eval_frequency: 30
num_eval_episodes: 3
target_score: 240

device: cuda

log_frequency: 10000
log_save_tb: true

seed: 1

hydra:
  job:
    name: ${env}
  run:
    dir: ./exp
