# Configuration for BipedalWalker-v3 environment with HER
env: "BipedalWalker-v3"
env_params: {}
agent_type: "agent_her"  # Using Hindsight Experience Replay

# Training parameters
episodes: 4000
max_steps: 500
target_score: 240
save_interval: 50

# Agent hyperparameters
lr_actor: 0.001
lr_critic: 0.001
batch_size: 64
buffer_size: 1000000
gamma: 0.99
tau: 0.001

# Noise parameters (HER typically uses different noise settings)
noise_sigma_initial: 0.3
noise_sigma_final: 0.1

# Logging
wandb: true
wandb_project: "BipedalWalker-v3-HER"

# Testing parameters
test_episodes: 100
render: true
record: false
video_folder: "./images"
video_freq: 10
with_noise: false
score_threshold: 200
