# Configuration for BipedalWalker-v3 environment
env: "BipedalWalker-v3"
env_params: {}
agent_type: "agent"  # Options: "agent", "agent_her"

# Training parameters
episodes: 4000
max_steps: 500
target_score: 240
save_interval: 50
load_checkpoint: false

# Agent hyperparameters
lr_actor: 0.001
lr_critic: 0.001
batch_size: 64
buffer_size: 1000000
gamma: 0.99
tau: 0.001

# Noise parameters
noise_sigma_initial: 0.2
noise_sigma_final: 0.04
noise_decay_score_threshold: 0.0
noise_score_decay_rate: 0.1

# Logging
wandb: true
wandb_project: "BipedalWalker-v3-Continuous"

# Testing parameters
test_episodes: 100
render: true
record: false
video_folder: "./images"
video_freq: 10
with_noise: false
score_threshold: 200