defaults:
  - agent: sac
  - _self_

env: BipedalWalker-v3
#env: BipedalWalkerHardcore-v3

experiment: test_exp

# Number of parallel environments (set to 1 for single env, 8+ for speedup)
num_envs: 10

num_train_steps: 2e6
max_episode_steps: 1500
replay_buffer_capacity: ${num_train_steps}

num_seed_steps: 5000

eval_frequency: 100
num_eval_episodes: 3
target_score: 240

device: cuda

log_frequency: 10000
log_save_tb: true

seed: 1

hydra:
  job:
    name: ${env}
  run:
    dir: ./exp
