defaults:
  - agent: sac
  - _self_

env: BipedalWalker-v3

experiment: test_exp

num_train_steps: 1e6
replay_buffer_capacity: ${num_train_steps}

num_seed_steps: 5000

eval_frequency: 10000
num_eval_episodes: 3

device: cuda

log_frequency: 10000
log_save_tb: true

save_video: true

seed: 1

hydra:
  job:
    name: ${env}
  run:
    dir: ./exp
